###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://sap.github.io/jenkins-library/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



# # # Project configuration
general:
  productiveBranch: 'main'
  buildTool: "mta"
# Stage configuration
stages:
  Build: 
    mavenExecuteStaticCodeChecks: false    # true, if you want to execute static code checks (default: false)
    npmExecuteLint: false 
  Release:
    cloudFoundryDeploy: true                                                # true, if you want to deploy to Cloud Foundry acceptance space. If you set this parameter to true, the cloudFoundryDeploy step is mandatory
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com" # for example, "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "32183c3dtrial"
    cfSpace: "dev"                           # the Cloud Foundry space, in which you want to execute uiVeri5 tests
    cfAppName: "dasc-showcase-srv"
    cfCredentialsId: "cf-credentialsid" ###
    deployType: "standard"
  Acceptance:
    kubernetesDeploy: false

# Step configuration
# steps:
#   mtaBuild:
#     buildTarget: 'CF'
#   cloudFoundryDeploy:
#     deployTool: 'mtaDeployPlugin'
#     deployType: 'standard'
#     cloudFoundry:
#       apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
#       org: 'SAP Internal - P&T CEE_cee-lac-eu'
#       space: 'dev'
#       credentialsId: 'cf-credentialsid'


